account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.user_signup, name='signup'),
    path('', views.dashboard, name='dashboard'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

bookmarks/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('images.urls', namespace='images')),
    path('social-auth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    # path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    # path('comment/', views.image_comment, name='comment'),
    # path('ranking/', views.image_ranking, name='ranking'),
    path('', views.image_list, name='list'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock  %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>
    <div id="header">
      <span class="logo">Bookmarks</span>
      {% if request.user.is_authenticated %}
        <ul class="menu">
        <li {% if section == "dashboard" %}class="selected"{% endif %}>
          <a href="{% url "account:dashboard" %}">My dashboard</a>
        </li>
        <li {% if section == "images" %}class="selected"{% endif %}>
          <a href="{% url "images:list" %}">Images</a>
        </li>
        <li {% if section == "people" %}class="selected"{% endif %}>
          <a href="{% url "account:user_list" %}">People</a>
        </li>
        </ul>
      {% endif %}
      <span class="user">
        {% if request.user.is_authenticated %}
          Hello {{ request.user }},
          <a href="{% url 'account:logout' %}">Logout</a>
          <a href="{% url 'account:edit_profile' %}">Edit Profile</a>
        {% else %}
          <a href="{% url 'account:login' %}">Log-in</a>
          <a href="{% url 'account:signup' %}">Sign-Up</a>
        {% endif %}
      </span>
    </div>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }}">
          {{ message|safe }}
          <a href="#" class="close">x</a>
        </li>
        {% endfor %}
      </ul>
    {% endif %}
    <div id="content">
      {% block content %}
      {% endblock  %}
    </div>

    <script
      src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js">
    </script>
    <script>
      var csrftoken = Cookies.get('csrftoken');
      function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
        beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
        }
      });
      $(document).ready(function(){
        {% block domready %}
        {% endblock %}
      });
    </script>
  </body>
</html>

templates/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/css.css" %}">
  </head>

  <body>
    <div style="padding-bottom:30px">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand">Bookmarks</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% if request.user.is_authenticated %}
            <ul class="navbar-nav" style="max-width:300px;">
              <li {% if section == "dashboard" %}class="nav-item active"
                  {% else %}class="nav-item" {% endif %} >
                <a class="nav-link" href="{% url "account:dashboard" %}">Dashboard</a>
              </li>
              <li {% if section == "dashboard" %}class="nav-item active"
                  {% else %}class="nav-item" {% endif %}>
                <a class="nav-link" href="{% url "images:list" %}">Images</a>
              </li>
              <li {% if section == "dashboard" %}class="nav-item active"
                  {% else %}class="nav-item" {% endif %}>
                <a class="nav-link" href="{% url "account:user_list" %}">Peoples</a>
              </li>
            </ul>
            <ul class="navbar-nav" style="position: absolute;right: 0;padding-right: 10px;">
              <li class="nav-item active ">
                <a class="nav-link" >Hello, {{ request.user.username }}</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'account:edit_profile' %}">Edit Profile</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
              </li>
            </ul>
          {% else %}
            <ul class="navbar-nav my-lg-0" style="float:right">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:login' %}">Login</a>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account:signup' %}">Signup</a>
              </li>
            </ul>
          {% endif %}
        </div>
      </nav>
    </div>

    <div id="content">
      {% block content %}
      {% endblock  %}
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script>
    var csrftoken = Cookies.get('csrftoken');
      function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
        beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
        }
      });
      $(document).ready(function(){
        {% block domready %}
        {% endblock %}
       });
     </script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
          crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
          crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static "js/javascript.js" %}">

    </script>
  </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Bookmarks</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Dashboard <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Images</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Peoples</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" method="get">
              <div class="input-group">
                  <input type="text" class="form-control" aria-label="Recipient's username" aria-describedby="button-addon2">
                  <div class="input-group-append">
                      <button class="btn btn-outline-primary" type="button" id="button-addon2">
                          <i class="fa fa-search"></i>
                      </button>
                  </div>
              </div>
          </form>
        </div>
    </nav>


    <div class="container-fluid gedf-wrapper">
      <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8 gedf-main">

            <!--- \\\\\\\Post-->
            <div class="card gedf-card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true">Make
                                a publication</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="images-tab" data-toggle="tab" role="tab" aria-controls="images" aria-selected="false" href="#images">Images</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
                            <div class="form-group">
                                <label class="sr-only" for="message">post</label>
                                <textarea class="form-control" id="message" rows="3" placeholder="What are you thinking?"></textarea>
                            </div>

                        </div>
                        <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">
                            <div class="form-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="customFile">
                                    <label class="custom-file-label" for="customFile">Upload image</label>
                                </div>
                            </div>
                            <div class="py-4"></div>
                        </div>
                    </div>
                    <div class="btn-toolbar justify-content-between">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">share</button>
                        </div>
                        <div class="btn-group">
                            <button id="btnGroupDrop1" type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                                <i class="fa fa-globe"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                                <a class="dropdown-item" href="#"><i class="fa fa-globe"></i> Public</a>
                                <a class="dropdown-item" href="#"><i class="fa fa-users"></i> Friends</a>
                                <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Just me</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Post /////-->
            <br><br><br>
            <!--- \\\\\\\Post-->
            <div class="card gedf-card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="mr-2">
                                <img class="rounded-circle" width="45" src="https://picsum.photos/50/50" alt="">
                            </div>
                            <div class="ml-2">
                                <div class="h5 m-0">LeeCross</div>
                            </div>
                        </div>
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary" style="width:120px;">Follow</button>
                        </div>
                    </div>

                </div>
                <div class="card-body">
                  <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>10 min ago</div>
                  <p class="card-text">
                      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo recusandae nulla rem eos ipsa praesentium esse magnam nemo dolor
                      sequi fuga quia quaerat cum, obcaecati hic, molestias minima iste voluptates.
                  </p>
                  <div class="card">
                    <img src="http://hdqwalls.com/wallpapers/tokyo-ghoul-re-4k-mk.jpg" class="card-img-top" alt="...">
                  </div>
                </div>
                <div class="card-footer">
                    <a href="#" class="card-link"><i class="fa fa-gittip"></i> Like</a>
                    <a href="#" class="card-link"><i class="fa fa-comment"></i> Comment</a>
                    <a href="#" class="card-link"><i class="fa fa-mail-forward"></i> Share</a>
                    <br><br>
                    {% if comment %}
                    <div class="card-body">
                      <div class="form-control">
                        <div class="d-flex">
                            <div class="mr-2">
                                <img class="rounded-circle" width="45" src="https://picsum.photos/50/50" alt="">
                            </div>
                            <div class="ml-2">
                                <div class="h5 m-0">@LeeCross</div>
                                <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>10 min ago</div>
                            </div>
                            <div class="ml-5 form-control">
                              <p class="card-text">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo recusandae nulla r
                              </p>
                            </div>
                        </div>
                      </div>
                    </div>
                    {% endif %}
                    <form id="comment-form" method="post">
                      {% csrf_token %}
                      <div class="form-group">
                        <textarea class="form-control" id="message" rows="3" placeholder="What are you thinking?"></textarea>
                      </div>
                      <div class="btn-group">
                          <button type="submit" class="btn btn-primary">Post Comment</button>
                      </div>
                    </form>
                </div>

            </div>
            <!-- Post /////-->

        </div>
      </div>
    </div>
    <br><br><br><br>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
          crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
          crossorigin="anonymous"></script>
  </body>
</html>

templates/test.html
{# <!-- {% for image in images %}
  <div class="image">
    <a href="{{ image.get_absolute_url }}">
      {% thumbnail image.image "300x300" crop="100%" as im %}
        <a href="{{ image.get_absolute_url }}">
          <img src="{{ im.url }}">
        </a>
      {% endthumbnail %}
    </a>
    <div class="info">
      <a href="{{ image.get_absolute_url }}" class="title">{{ image.title }}</a>
    </div>
  </div>
{% endfor %} --> #}
<form class="form-inline col-lg-8 my-lg-0" style="max-width:800px;" method="get">
  <div class="input-group" style="width:700px;">
    <input type="text" class="form-control" aria-label="Recipient's username" aria-describedby="button-addon2">
    <div class="input-group-append">
      <button class="btn btn-outline-primary" type="button" id="button-addon2">
          <i class="fa fa-search"></i>
      </button>
    </div>
  </div>
</form>







var page = 1;
var empty_page = false;
var block_request = false;
$(window).scroll(function() {
  var margin = $(document).height() - $(window).height() - 200;
  if ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
    block_request = true;
    page += 1;
    $.get('?page=' + page, function(data) {
      if(data == '') {
        empty_page = true;
      }
      else {
        block_request = false;
        $('#image-list').append(data);
      }
    });
  }
});


$("#add-comment").click(function(e) {
  var str = $("#comment-form").serialize();
  $.post('{% url "images:like" %}',
    {
      id: $(this).data('id'),
      action: $(this).data('action')
    },
  function(data) {
    var data = JSON.parse(data);
    var list = $('<div class="card gedf-card">');
    var item = $('<div class="card-footer">').html(comments);
    if (data) {
      alert(data);
      comments =""
          ;
      list.append(item);
    }
    $("#output").html(list);
  });
});

$('a.comment').click(function(e){
  e.preventDefault();
  $.post('{% url "images:comment" %}',
  {
    id: $(this).data('id'),
    action: $(this).data('action')
  },
  function(data){
    if (data)
    {

    }
  }
  );
});

<script>

	$("#add-comment").click(function(e) {
		var str = $("#comment-form").serialize();
		$.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action')
      },
		function(data) {
			var data = JSON.parse(data);
			var list = $('<div class="card gedf-card">');
			var item = $('<div class="card-footer">').html(comments);
			if (data) {
				comments =
            "<div class='form-control'>" + "<div class='d-flex'>" + "<div class='mr-2'>"
            + {% thumbnail data[0].user.avatar "45x45" crop="100%" as im %}
            + "<img class='rounded-circle' width='45' src='{{ im.url }}'>"
            + {% endthumbnail %}
            + "</div>" + "<div class='ml-2'>"
            + "<div class='h5 m-0'>{{ comment.user.username }}</div>"
            + "<div class='text-muted h7 mb-2'> <i class='fa fa-clock-o'></i>{{ comment.created }}</div>"
            + "</div>" + '<div class="ml-5 form-control">' + '<p class="card-text">'
            + {{ data[0].body|linebreaks }}
            + "</p>" + "</div>" + "</div>" + "</div>" + "</div>";

				var item = $('<div class="card-footer">').html(comments);
				list.append(item);
			}
			$("#output").html(list);
		});
  });
</script>