account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.user_signup, name='signup'),
    path('', views.dashboard, name='dashboard'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('users/', views.user_list, name='user_list'),
    path('users/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

bookmarks/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('images.urls', namespace='images')),
    path('social-auth/', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    # path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    # path('comment/', views.image_comment, name='comment'),
    # path('ranking/', views.image_ranking, name='ranking'),
    path('', views.image_list, name='list'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey

# Create your models here.

class Comment(models.Model):
    content_type   = models.ForeignKey(ContentType, null=True, on_delete=models.CASCADE)
    object_id      = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    user    = models.ForeignKey(settings.AUTH_USER_MODEL, null=True ,related_name='users_comment', on_delete=models.CASCADE)
    body    = models.CharField(max_length=512, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created',]

    def __str__(self):
        return 'Comment by {} on {}'.format(self.user, "test")

class Image(models.Model):
    user           = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    title          = models.CharField(max_length=100)
    slug           = models.SlugField(blank=True, max_length=200)
    url            = models.URLField(blank=True)
    image          = models.ImageField(upload_to='images/%Y/%m/%d/', blank=True)
    body           = models.TextField(blank=True)
    created        = models.DateField(auto_now_add=True, db_index=True)
    users_like     = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)
    total_likes    = models.PositiveIntegerField(db_index=True, default=0)
    comments       = GenericRelation(Comment, blank=True, null=True)

    class Meta:
        ordering = ['-created',]

    def __str__(self):
        return self.title

    def published():
        now = timezone.now()
        last_minute = now - datetime.timedelta(seconds=60)
        return last_minute

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image, self).save(*args, **kwargs)

images/forms.py
from django import forms
from .models import Image, Comment
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model   = Image
        fields  = ('title', 'body', 'image', 'url')
        widgets = {
            'image' : forms.FileInput(attrs={'name':'image', 'class':'custom-file-input', 'id':'customFile'}),
            'url'   : forms.URLInput(attrs={'name':'url','class':'form-control' ,'placeholder':'Post Image URL'}),
            'body'  : forms.Textarea(attrs={'name':'desc',"class":"form-control", "id":"message", "rows":"3", "placeholder":"What are you thinking?"}),
            'title' : forms.TextInput(attrs={'name':'desc',"class":"form-control", "id":"message", "rows":"1", "placeholder":"Image Title (required)"}),
        }

    def clean(self):
        cd = self.cleaned_data
        if not cd['image'] and not cd['url']:
            raise forms.ValidationError('Please upload an image or give image url.')
        return cd

    def clean_url(self):
        url = self.cleaned_data['url']
        if url:
            valid_extensions = ['jpg', 'jpeg']
            extension        = url.rsplit('.',1)[1].lower()
            if extension not in valid_extensions:
                raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url

    # def save(self, force_insert=False, force_update=False, commit=True):
    #     image = super(ImageCreateForm, self).save(commit=False)
    #     image_url = self.cleaned_data['url']
    #     image_name = '{}.{}'.format(slugify(image.title), image_url.rsplit('.',1)[1].lower())
    #
    #     response = request.urlopen(image_url)
    #     image.image.save(image_name, ContentFile(response.read()), save=False)
    #
    #     if commit:
    #         image.save()
    #     return image

class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs=
                {"name":"body", "class":"form-control" ,"id":"message" ,"rows":"3" ,"placeholder":"What are you thinking?"}
                    )
                )
    class Meta:
        model = Comment
        exclude = ('content_type', 'object_id', 'content_object')

images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from common.decorators import ajax_required
from .forms import ImageCreateForm, CommentForm
from .models import Image, Comment
from actions.utils import create_action
from django.conf import settings
import redis

r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)


@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            create_action(request.user, "Bookmarked Image", new_image)
            messages.success(request, "Image Added Successfully")
            return redirect(new_image.get_absolute_url())
    else:
        form = ImageCreateForm()
    context = {
        'form'    :   form,
        'section' :   'images',
    }
    return render(request, "images/create.html", context)

# @login_required
# def image_detail(request, id, slug):
#         image = get_object_or_404(Image, id=id, slug=slug)
#         total_views = r.incr('image:{}:view'.format(image.id))
#         # increment image ranking by 1
#         r.zincrby('image_ranking', image.id, 1)
#         context = {
#             'image'       :  image,
#             'section'     :  'images',
#             'total_views' : total_views,
#         }
#         return render(request, "images/detail.html", context)

@login_required
def image_list(request):
    comment = CommentForm()
    if request.method == 'POST':
        comment = CommentForm(request.POST)
        form    = ImageCreateForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            create_action(request.user, "Bookmarked Image", new_image)
            messages.success(request, "Image Added Successfully")
            return redirect('images:list')
        else:
            print("Form Not Valid")
        if comment.is_valid():
            id = request.POST.get('image')
            body = request.POST.get('body')
            image = Image.objects.get(id=id)
            image.comments.create(user=request.user, body=body)
            return redirect('images:list')

    else:
        form    = ImageCreateForm()
    images    = Image.objects.all()
    comments  = Comment.objects.all()
    paginator = Paginator(images, 4)
    page      = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, "images/list_ajax.html", {"images":images, "section":"images", "form":form, "CommentForm" : comment,"comments": comments,})
    context = {
        "section"     : "images",
        "images"      : images,
        "comments"    : comments,
        "form"        : form,
        "CommentForm" : comment,
    }
    return render(request, "images/list.html", context)

@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action   = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, "likes", image)
            else:
                image.users_like.remove(request.user)
        except:
            pass
    return JsonResponse({'status':'ok'})

# @ajax_required
# @login_required
# @require_POST
# def image_comment(request):
#     image_id = request.POST.get('id')
#     action   = request.POST.get('action')
#     body     = request.POST.get('body')
#     response = None
#     if image_id and action:
#         try:
#             image = Image.objects.get(id=image_id)
#             if action == 'comment':
#                 image.users_comment.add(request.user)
#                 response = image.comments.create(user=request.user, body=body)
#                 create_action(request.user, "commented on", image)
#         except Exception as e:
#             print(e)
#     return JsonResponse(response)

# @login_required
# def image_ranking(request):
#     image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
#     image_ranking_ids = [int(id) for id in image_ranking]
#     # get most viewed images
#     most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
#     most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
#     return render(request,'images/ranking.html',{'section': 'images','most_viewed': most_viewed})

templates/images/create.html
{% extends "base.html" %}

{% block title %}Bookmark Image{% endblock  %}

{% block content %}
  <h1>Bookmark an image</h1>
  <img src="{{ request.GET.url }}" class="image-preview">
  <form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Bookmark it">
  </form>
{% endblock  %}

templates/images/detail.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %}{{ image.title }}{% endblock %}


{% block content %}
  <h1>{{ image.title }}</h1>
    {% thumbnail image.image "300" as im %}
    <a href="{{ image.image.url }}">
    <img src="{{ im.url }}" class="image-detail">
    </a>
  {% endthumbnail %}

  {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div class="image-info">
      <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span>
          like{{ total_likes|pluralize }}
        </span>
        <span class="count">
          {{ total_views }} view{{ total_views|pluralize }}
        </span>
        <a href="#" data-id="{{ image.id }}"
          data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
      </div>
      {{ image.description|linebreaks }}
    </div>
    <div class="image-likes">
      {% for user in image.users_like.all %}
        <div>
          {% if user.avatar %}
            <img src="{{ user.avatar.url }}">
          {% endif %}
          <p>{{ user.username }}</p>
        </div>
        {% empty %}
        Nobody likes this image yet.
      {% endfor %}
    </div>
  {% endwith %}
{% endblock %}


{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}',
    {
      id: $(this).data('id'),
      action: $(this).data('action')
    },
    function(data){
      if (data['status'] == 'ok')
      {
        var previous_action = $('a.like').data('action');
        // toggle data-action
        $('a.like').data('action', previous_action == 'like' ?
          'unlike' : 'like');
        // toggle link text
        $('a.like').text(previous_action == 'like' ? 'Unlike' :
        'Like');
        // update total likes
        var previous_likes = parseInt($('span.count .total').text());
        $('span.count .total').text(previous_action == 'like' ?
          previous_likes + 1 : previous_likes - 1);
      }
    }
    );
  });
{% endblock %}

templates/images/list.html
{% extends "base2.html" %}

{% load thumbnail %}


{% block title %} Images Bookmarked {% endblock  %}

{% block content %}
  <div class="container-fluid gedf-wrapper">
    <div class="row">
      <div class="col-md-2">
      </div>
      <div class="col-md-8 gedf-main">
        <!--- \\\\\\\Post-->
        <div class="card gedf-card">
          <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true">Make
                      a publication</a>
              </li>
            </ul>
          </div>
            <div class="card-body">
              <form action="." method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="tab-content" id="myTabContent">
                  <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
                    <div class="form-group">
                      {{ form.title }}
                    </div>
                    <div class="form-group">
                      {{ form.body }}
                    </div><br>
                    <div class="form-group">
                      {{form.non_field_errors}}
                      <div class="custom-file">
                        {{ form.image }}
                        <label class="custom-file-label" for="customFile">Upload image</label><p style="color:red;padding-top:6px" align="center">OR</p>
                        {{ form.url }}
                      </div>
                    </div>
                  </div>
                </div>
                <div class="btn-toolbar justify-content-between">
                  <div class="btn-group">
                      <button type="submit" class="btn btn-primary">share</button>
                  </div>
                </div>
              </form>
            </div>
        </div>
        <!-- Post /////--><br><br>

        <!--- \\\\\\\Post-->
        <div id="image-list">
          {% include "images/list_ajax.html" %}
        </div>
        <!-- Post /////-->
      </div>
    </div>
  </div>
{% endblock  %}

{% block domready %}
  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
      block_request = true;
      page += 1;
      $.get('?page=' + page, function(data) {
        if(data == '') {
          empty_page = true;
        }
        else {
          block_request = false;
          $('#image-list').append(data);
        }
      });
    }
  });


  $('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url "images:like" %}',
    {
      id: $(this).data('id'),
      action: $(this).data('action')
    },
    function(data){
      if (data['status'] == 'ok')
      {
        var previous_action = $('a.like').data('action');
        // toggle data-action
        $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
        // toggle link text
        $('a.like').text(previous_action == 'like' ? ' unLike' : ' Like');
        // update total likes
        var previous_likes = parseInt($('span.count .total').text());
        $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
      }
    }
    );
  });


  $('a.follow').click(function(e){
    e.preventDefault();
    $.post('{% url "account:user_follow" %}',
    {
      id: $(this).data('id'),
      action: $(this).data('action')
    },
    function(data){
      if (data['status'] == 'ok') {
        var previous_action = $('a.follow').data('action');
        // toggle data-action
        $('a.follow').data('action', previous_action == 'follow' ? 'unfollow' : 'follow');
        // toggle link text
        $('a.follow').text(previous_action == 'follow' ? 'unFollow' : 'Follow');
        // update total followers
        var previous_followers = parseInt($('span.count .total').text());
        $('span.count .total').text(previous_action == 'follow' ? previous_followers + 1 : previous_followers - 1);
      }
    }
    );
  });
{% endblock  %}

templates/images/list_ajax.html
{% load thumbnail %}

{% for image in images %}
  <!--- \\\\\\\Post-->
  <div class="card gedf-card">
    <div class="card-header">
      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex justify-content-between align-items-center">
          <div class="mr-2">
            {% thumbnail image.user.avatar "45x45" crop="100%" as im %}
              <a href="{{ image.user.get_absolute_url }}" target="_blank">
                <img class="rounded-circle" src="{{ im.url }}">
              </a>
            {% endthumbnail %}
          </div>
            <div class="ml-2">
              <div class="h5 m-0"><a href="{{ image.user.get_absolute_url }}" target="_blank">{{ image.user.username }}</a></div>
              <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i> {{ image.created }}</div>
            </div>
        </div>
          {% if request.user == image.user %}
          {% else %}
            <div class="btn-group">
              <a href="#" data-id="{{ image.user.id }}"
                  data-action="{% if request.user in image.user.followers.all %}un{% endif %}follow"
                  class="follow button btn btn-primary" style="width:120px;">
                {% if request.user not in image.user.followers.all %}
                  Follow
                {% else %}
                  unFollow
                {% endif %}
              </a>
            </div>
          {% endif %}
      </div>

    </div>
      <div class="card-body">

        <p class="card-text">
            {{ image.body|linebreaks }}
        </p>
        <div class="card">
          <a href="{% if image.image %}{{ image.image.url }}{% endif %}" target="_blank">
            <img src="{% if image.image %}{{ image.image.url }}{% else %}{{ image.url }}{% endif %} " class="card-img-top">
          </a>
        </div>
      </div>
      <div class="card-footer">
        {% with total_likes=image.users_like.count users_like=image.users_like.all %}
          <a href="#" data-id="{{ image.id }}"
                data-action="{% if request.user in users_like %}un{% endif %}like"
                class="like button card-link fa fa-gittip">
            {% if request.user not in users_like %} Like{% else %} unLike{% endif %}
          </a>
          <a class="card-link"><i class="fa fa-comment"></i> Comment</a>
          <div class="card-link dropdown">
            <i class="card-link fa fa-mail-forward"></i> Share
            <div class="dropdown-content">
              <a class="btn btn-lg btn-fb" href="https://www.facebook.com/sharer/sharer.php?u=http://127.0.0.1{{ image.get_absolute_url|urlencode }}" target="_blank" ><i class="fa fa-facebook-f pr-1"></i></a>
              <a class="btn btn-lg btn-tw" href="http://twitter.com/share?url=http://127.0.0.1{{ image.get_absolute_url|urlencode }}&amp;text={{ post.title }}" target="_blank"><i class="fa fa-twitter"></i></a>
              <a class="btn btn-lg btn-in" href="http://www.linkedin.com/shareArticle?mini=true&amp;url=http://127.0.0.1{{ image.get_absolute_url|urlencode }}&amp;title={{ image.title }}&amp;ro=false&amp;summary=&amp;source=" target="_blank"><i class="fa fa-linkedin"></i></a>
            </div>
          </div>
          <p class="float-right" style="color:blue;">{{ total_likes }} like{{ total_likes|pluralize }}</p>
        {% endwith %}
          <br><br>
        {% with image.comments.all as comments %}
        {% if comments %}
        {% for comment in comments %}
          <div class="card-body">
            <div>
              <div class="d-flex">
                  <div class="mr-2">
                    {% thumbnail comment.user.avatar "45x45" crop="100%" as im %}
                      <img class="rounded-circle" width="45" src="{{ im.url }}" alt="">
                    {% endthumbnail %}
                  </div>
                  <div class="ml-2">
                      <div class="h5 m-0">{{ comment.user.username }}</div>
                      <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i> {{ comment.created|timesince }} ago</div>
                  </div>
                  <div class="" style="padding-left:50px;">
                    <p class="card-text">
                      {{ comment.body|linebreaks }}
                    </p>
                  </div>
              </div>
            </div>
          </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% if CommentForm %}
          <form id="comment-form" action="." method="post">
            {% csrf_token %}
            <div class="form-group">
              {{ CommentForm.body }}
            </div>
            <input type="hidden" name="image" value="{{ image.id }}">
            <input id="id_user" name="user" value="{{ user.id }}" hidden>
            <div class="btn-group">
                <button type="submit" class="btn btn-primary">
                    Post Comment
                </button>

            </div>
          </form>
        {% endif %}
      </div>

  </div>
  <br><br><br>
  <!-- Post /////-->
{% endfor %}

templates/images/ranking.html
{% extends "base.html" %}

{% block title %}Images ranking{% endblock %}

{% block content %}
  <h1>Images ranking</h1>
  <ol>
    {% for image in most_viewed %}
      <li>
        <a href="{{ image.get_absolute_url }}">
          {{ image.title }}
        </a>
      </li>
    {% endfor %}
  </ol>
{% endblock %}